Feature/set interest
wafflestudio/guam-community-client pull request #27
Opened 2022-01-09 15:17 UTC by YeonghyeonKO

- [ ] 핵심: 관심사 설정 하단 모달 개발

- [ ] 쪽지함/휴지통 아이콘 패딩 조정

- [ ] 쪽지함 편집 페이지에서는 쪽지함 세부 페이지로 이동할 수 없도록 onTap 비활성화

2022-01-13 13:58 UTC, gajagajago commented on lib/screens/boards/posts/post_list.dart
> +                      builder: (BuildContext context, StateSetter myState) {
StatefulBuilder, StateSetter syntax를 처음 알게 됐는데 아래 정도로 정리하고 있으면 될까요?
- setState 함수를 위젯 생성자의 파라미터로 전달하지 않아도 된다
- Stateful widget의 state들을 자유롭게 변경할 수 있다

2022-01-13 14:00 UTC, gajagajago commented on lib/screens/boards/posts/post_list.dart
> +                                      _interestType(context, myState, '#개발'),
_interestType 위젯 생성하는 모든 부분에서 context를 파라미터로 전달할 필요는 없을 것 같습니다. 
```suggestion
                                      _interestType(myState, '#개발'),
```

2022-01-13 14:01 UTC, gajagajago requested changes
간단한 수정 요청 사항 남겼습니다. 확인 후 re-request 부탁드립니다 !

2022-01-14 01:27 UTC, YeonghyeonKO commented on lib/screens/boards/posts/post_list.dart
> +                      builder: (BuildContext context, StateSetter myState) {
네 맞습니다. 애초에 전달하지 않아도 된다기보다는 `전달해야하는 상황에서는 StateSetter로 새롭게 전달해야 한다`가 맞는 느낌입니다. 저는 하단 모달 외에는 실험해보지 않았는데, StatefulBuilder로 context, state를 분리할 수 있을 것 같기도 합니다.

하단 모달은 StateSetter 타입의 state를 넘겨주지 않으면 state가 아예 정의되어 있지 않은 Stateless 상태인 걸로 추정됩니당

2022-01-14 01:30 UTC, YeonghyeonKO commented on lib/screens/boards/posts/post_list.dart
> +                                      _interestType(context, myState, '#개발'),
그렇네요 수정했습니다!

2022-01-14 01:31 UTC, YeonghyeonKO commented on lib/screens/boards/posts/post_list.dart
> +  Widget _interestType(BuildContext context, StateSetter myState, String interest) {
수정완료

2022-01-14 01:31 UTC, YeonghyeonKO commented on lib/screens/boards/posts/post_list.dart
> +      builder: (context) => InkWell(
수정완료

2022-01-14 01:51 UTC, gajagajago commented on lib/screens/boards/posts/post_list.dart
> +                                      _interestType(context, myState, '#개발'),
ㅋㅋ신기술은 아닙니다..ㅎㅎ 전부터 있었긴 합니다 안 썼을 뿐

2022-01-14 01:52 UTC, gajagajago approved these changes
lgtm

2022-01-14 06:13 UTC, merged