검색 탭
wafflestudio/guam-community-client pull request #32
Opened 2022-01-16 12:31 UTC by gajagajago

Actions

- [ ] Search with query string
- [ ] Previous search history (MAX 5, stored locally)
- [ ] Search by clicking previous search word
- [ ] Sort by filters 

Not Implemented
- Boards segments under search tab. Necessary..?

2022-01-16 13:59 UTC, YeonghyeonKO requested changes
<img width="829" alt="image" src="https://user-images.githubusercontent.com/46114393/149663126-f86cd57d-e828-43b3-b18c-9d1f3310efb3.png">
게시판별 전환 구현이 안되어 있습니다!

2022-01-16 13:59 UTC, YeonghyeonKO commented on lib/screens/search/search_feed.dart
> +// }
추후에 StatefulWidget으로 바꾸실 때를 대비하여 남겨두신 건가요?

2022-01-16 13:59 UTC, YeonghyeonKO commented on lib/screens/search/search_app_textfield.dart
> +  static final controller = TextEditingController();
![image](https://user-images.githubusercontent.com/46114393/149662954-b89d5bd3-83bd-4e4d-8dd2-42dc2f0b64b0.png)

이러한 에러가 뜹니다..!

2022-01-16 13:59 UTC, YeonghyeonKO commented on lib/screens/search/search_word.dart
> +      mainAxisAlignment: MainAxisAlignment.spaceBetween,
spaceBetween으로 최대한 Text 부분이랑 (X) 버튼이랑 떨어뜨려두시긴 했는데 디자인상으로 다소 차이가 나네요!
<img width="830" alt="image" src="https://user-images.githubusercontent.com/46114393/149663092-b071d45e-77ae-441b-9b78-8e575c897466.png">

2022-01-16 14:00 UTC, YeonghyeonKO commented on lib/screens/search/search_app_textfield.dart
> +  static final controller = TextEditingController();
이 에러는 `hot restart` 처리하면 잠시 없어지긴 하는데 `hot reload` 시에는 계속 남아 있네요

2022-01-16 14:12 UTC, gajagajago commented on lib/screens/search/search_feed.dart
> +// }
아뇨 ㅋㅋ 삭제 삭제..

2022-01-16 14:22 UTC, gajagajago commented on lib/screens/search/search_word.dart
> +      mainAxisAlignment: MainAxisAlignment.spaceBetween,
padding btw 0 주면 될 거 같습니다 v

2022-01-16 14:31 UTC, gajagajago commented on lib/screens/search/search_app_textfield.dart
> +  static final controller = TextEditingController();
최근 검색어 클릭하면 텍스트 필드 글자 align 해주려고 static controller를 선언한 탓이네요... 어떻게 바꿔야 할 지 고민 좀 해보겠습니다.

2022-01-16 14:48 UTC, gajagajago commented on lib/screens/search/search_app_textfield.dart
> +  static final controller = TextEditingController();
Fix 했습니다. Static 하게 사용하는 컨트롤러(직접적인 value 변경 외에도, 클래스 외부에서 value 변경을 합니다 -- by 최근 검색어 클릭) 라, 조금 irregular 하긴 하지만 dispose 하지 않는 방식을 선택했습니다.

2022-01-17 03:26 UTC, YeonghyeonKO reviewed
수정 커밋은 확인했습니다! 전체 레이아웃 기획 후딱 하겠습니다 ㅎㅎ

2022-01-17 03:26 UTC, YeonghyeonKO commented on lib/screens/search/search_app_textfield.dart
> +  static final controller = TextEditingController();
흥미롭네요 dispose 때문에 오히려 밖에서 에러가 떴군요

2022-01-24 05:47 UTC, YeonghyeonKO reviewed
@gajagajago 신규 디자인대로 업데이트 끝나면 review request 주셔요~

2022-01-24 13:04 UTC, gajagajago commented
@YeonghyeonKO Post-preview 를 홈 탭, 검색 탭에서 둘 다 사용하는데, 현재 어떤 탭에 위치하고 있는지 알 수 있는 방법이 있을까요?

2022-01-24 13:10 UTC, YeonghyeonKO commented
@gajagajago boardType 값으로 구별 가능합니다! 현재는 임시방편으로 모든 탭에 다 똑같이 보이게 했는데 그 윗단에서 boardType에 맞도록 필터링하여 뿌려줄 수 있습니다.

2022-01-25 14:36 UTC, gajagajago commented
넵! HomeProvider의 idx를 TabItem enum으로 type casting해서 쓰면 무리 없을 것 같습니다 !

2022-01-27 07:44 UTC, gajagajago commented
@YeonghyeonKO 리뷰 한번 부탁드립니다~!

2022-01-27 14:17 UTC, YeonghyeonKO requested changes
디자인 변경된 사항이 반영되어 있지 않습니다!

2022-01-27 14:17 UTC, YeonghyeonKO commented on lib/screens/boards/posts/preview/post_preview_home_tab.dart
> +              ),
post_preview_home_tab 에서는 카드 내에서 어느 게시판인지 보여주지 않습니다! 관심사와 시간이 동일한 row에 놓이게 됩니다!
(디자인 참고)

2022-01-27 14:17 UTC, YeonghyeonKO commented on lib/screens/search/search_app_textfield.dart
> +                ),
해당 부분 디자인이 다소 변경되었는데 참고 바랍니다!
<img width="918" alt="image" src="https://user-images.githubusercontent.com/46114393/151375689-c160c9aa-8418-40f4-905a-03567f538260.png">

2022-01-27 14:17 UTC, YeonghyeonKO commented on lib/screens/search/search_app_textfield.dart
> +                ),
- 검색 탭 배경 색 제거
- 돋보기 크기 및 색상 변화
- 검색어 입력 시 검색창 색상 변화 (검색창 색상 변화는 /signup Route로 들어가셔서 닉네임 입력 때 발생하는 효과 참고)
- 최근검색어 글씨 색 / 최근검색어 삭제 버튼
- 최근순 & 추천순 오른쪽 padding

2022-01-27 14:48 UTC, gajagajago commented on lib/screens/search/search_app_textfield.dart
> +                ),
아 여기도 디자인이 바뀌었나보네요 넵!

2022-01-28 06:16 UTC, YeonghyeonKO commented on lib/screens/boards/posts/preview/post_preview_home_tab.dart
> +              ),
@gajagajago 이 부분 슬랙에 이슈로 남겼습니다! 어색하긴 하네요...

2022-02-01 04:00 UTC, gajagajago commented on lib/screens/search/search_app_textfield.dart
> +                ),
최근순 & 추천순 오른쪽 padding

이거만 크리티컬 하지 않으면 반영 안 하겠습니다. common 썼는데 걸리는 곳 너무 많고, 그렇다고 전체 컨테이너 패딩을 조정하기엔 또 너무 마이너한 이슈라서요.

2022-02-01 04:17 UTC, gajagajago commented
작업은 다 됐는데 디자인 아이콘 하나 받아야 돼서 머지 보류..!

2022-02-01 05:16 UTC, gajagajago commented
ready for review!

2022-02-01 12:27 UTC, YeonghyeonKO approved these changes
이 부분만 확인 부탁드려요! 슬랙에 남긴 기획/디자인 변경 사항은 추가 PR로 제가 하겠습니다!

2022-02-01 12:46 UTC, gajagajago commented on lib/screens/search/search_app_textfield.dart
> +  static final controller = TextEditingController();
네 알겠습니다! 확인 다시 해볼게요

2022-02-01 13:56 UTC, gajagajago commented on lib/screens/search/search_app_textfield.dart
> +  static final controller = TextEditingController();
위 이슈 관련해, flutter engine 쪽 issue가 있었고 이 문제가 ver. 2.8.0 이후 해결된 것을 확인했습니다 [링크](https://github.com/flutter/engine/pull/29550)
이에 따라 flutter version upgrade 2.5.3 -> 2.8.1 진행했고 dispose 코드도 넣었습니다. 현재는 재현 되지 않습니다.

2022-02-01 13:56 UTC, gajagajago commented
머지하겠습니다.

2022-02-01 13:56 UTC, merged