Feature/other profile
wafflestudio/guam-community-client pull request #35
Opened 2022-01-30 13:34 UTC by YeonghyeonKO

- [ ] 타인 프로필 열람 기능

- [ ] 쪽지 보내기 하단 모달

2022-02-01 05:16 UTC, gajagajago commented
will review now

2022-02-01 07:46 UTC, gajagajago requested changes
Restart 시 마다 재현되는 error가 존재합니다. 해당 error 해결 후 리뷰하는 게 좋을 것 같고, 이참에 rebase도 이번 브랜치에 가능하면 적용해보면 좋을 것 같습니다. 
```
flutter: NoSuchMethodError: The method '-' was called on null.
Receiver: null
Tried calling: -(1)
flutter: NoSuchMethodError: The method '-' was called on null.
Receiver: null
Tried calling: -(1)

══╡ EXCEPTION CAUGHT BY FOUNDATION LIBRARY ╞════════════════════════════════════════════════════════
The following assertion was thrown while dispatching notifications for OtherProfile:
setState() or markNeedsBuild() called during build.
This _InheritedProviderScope<OtherProfile> widget cannot be marked as needing to build because the
framework is already in the process of building widgets.  A widget can be marked as needing to be
built during the build phase only if one of its ancestors is currently building. This exception is
allowed because the framework builds parent widgets before children, which means a dirty descendant
will always be built. Otherwise, the framework might not visit this widget during this build phase.
The widget on which setState() or markNeedsBuild() was called was:
  _InheritedProviderScope<OtherProfile>
The widget which was currently being built when the offending call was made was:
  _InheritedProviderScope<Messages>

```

2022-02-03 12:35 UTC, YeonghyeonKO commented
@gajagajago 

```
══╡ EXCEPTION CAUGHT BY FOUNDATION LIBRARY ╞════════════════════════════════════════════════════════
The following assertion was thrown while dispatching notifications for OtherProfile:
setState() or markNeedsBuild() called during build.
This _InheritedProviderScope<OtherProfile> widget cannot be marked as needing to build because the
framework is already in the process of building widgets.  A widget can be marked as needing to be
built during the build phase only if one of its ancestors is currently building. This exception is
allowed because the framework builds parent widgets before children, which means a dirty descendant
will always be built. Otherwise, the framework might not visit this widget during this build phase.
The widget on which setState() or markNeedsBuild() was called was:
  _InheritedProviderScope<OtherProfile>
The widget which was currently being built when the offending call was made was:
  _InheritedProviderScope<Messages>
```

위 에러는 Provider에서 정의한 비동기 함수가 Build 이전에 새로운 페이지에서 렌더링되어 발생하는 문제였습니다.
따라서 아래처럼 Build 이후로 delay 시키는 Future 함수로 감싸주어 해결했습니다.

```
Future.delayed(
      Duration.zero,
      () async => context.read<OtherProfile>().getUserProfile(widget.userId),
);
```

이와는 별개로 아래 문제는 해결되지 않았기 때문에 추가로 수정하도록 하겠습니다.

```
flutter: NoSuchMethodError: The method '-' was called on null.
Receiver: null
Tried calling: -(1)
```

2022-02-03 13:41 UTC, YeonghyeonKO commented
@gajagajago 

```
flutter: NoSuchMethodError: The method '-' was called on null.
Receiver: null
Tried calling: -(1)
```
위 에러는 `Future<Profile> getUserProfile(int userId)` 함수에서 API 붙이기 전까지 userId-1로 dummy data의 idx를 처리하던 로직 때문에 발생했습니다. userId가 null인 경우 -1 을 하지 않도록 중간에서 return null로 함수에서 빠지는 방식으로 해결했습니다.

```
      // API 붙일 때는 (idx - 1) 방식 대신 직접 userId를 넘길 예정.
      if (userId == null) return null;

      Map<String, dynamic> profile = profiles[userId-1];
```

2022-02-03 16:10 UTC, closed without merging