Feature/other profile2
wafflestudio/guam-community-client pull request #41
Opened 2022-02-03 16:11 UTC by YeonghyeonKO

- [ ] 내 프로필 / 타인 프로필 구별하기 (쪽지보내기 버튼 안보이게 처리 등)

- [ ] 타인 프로필에서 쪽지 보내기

2022-02-04 00:50 UTC, YeonghyeonKO commented
@gajagajago 준열님 이 PR에서처럼 merge from develop 커밋이 없으면 딱히 rebase가 의미가 없는거죠?

2022-02-05 02:20 UTC, gajagajago commented
> @gajagajago 준열님 이 PR에서처럼 merge from develop 커밋이 없으면 딱히 rebase가 의미가 없는거죠?

develop에서 이 브랜치를 fork한 이후에 develop에 다른 커밋이 들어간 경우 rebase는 의미 있습니다! 왜냐하면 저희가 주로 PR 올리기 전에 무조건 최신 develop을 한번 머지를 했었는데, 그 경우 해당 PR에서 변경하지 않은 코드들까지 commit history에 추가되어 PR 리뷰량이 늘어났었습니다. Rebase의 경우 다른 브랜치에서 develop에 커밋이 들어간 내용은 해당 PR의 commit history 반영에서 제외되기 때문에, 불필요한 리뷰량이 줄어듭니다.

2022-02-05 07:19 UTC, gajagajago requested changes
Review 했습니다. Authenticate과 Profile을 다루는 방법에 있어 Guam 1가 차이점이 생긴 것 같은데, 개인적으론 기존 방식이 낫다고 생각이 들었습니다! 혹시 논의하고 싶으신 내용 있으시면 충분히 얘기해보고 결정해도 좋습니다 🤗 고생하셨습니다.

2022-02-05 07:19 UTC, gajagajago commented on lib/commons/bottom_modal/bottom_modal_with_message.dart
> +              onPressed: () => func,
```suggestion
              onPressed: func,
```

2022-02-05 07:19 UTC, gajagajago commented on lib/providers/profiles/profiles.dart
>  class MyProfile with ChangeNotifier {
MyProfile 과 OtherProfile provider를 구분하는 방법에 대해 조금.. 반대하는 입장입니다. 아니, profile provider가 굳이 필요한가 ? 라고 생각합니다. 

Guam 1 을 보면 authenticate provider에서 내 프로필은 아래와 같이 처리합니다. 해당 코드는 소셜 로그인 등에서도 필요한 코드이고, 소셜 로그인은 가장 초입에 유저가 만나는 코드라 authenticate provider의 scope에만 들어갈 것이라, authenticate 에서 들고 있는게 좋을 것 같습니다. 
```
    final authProvider = context.watch<Authenticate>();
    final profile = authProvider.me;
```
타인 profile을 fetch하는 getUserProfile 코드도 authenticate 안에 getUserProfile() 로 원래처럼 두는 게 낫다고 생각합니다. 왜냐면 authenticate provider는 거의 최상단에 있는 글로벌한 provider인데, profile provider를 새로 만들면 또 거의 모든 곳에 넣어줘야 돼서 입니다. 굳이 OtherProfile을 위한 Profile provider를 만들기보단, 어짜피 원래 있는 authenticate provider 안에서 해결하는 기존 방식으로 놔두면 어떨까요?

2022-02-05 07:19 UTC, gajagajago commented on lib/screens/profiles/other_profiles_body.dart
> +          if (!isMine) MessageSendButton(profile),
나인지 확인하는 방식 역시, 기존에 isMe() 코드를 활용하는 방향이 좋을 것 같습니다. 그러면 굳이 파라미터로 isMe를 넘겨주지 않아도 되니까요.

2022-02-06 12:47 UTC, gajagajago approved these changes

2022-02-06 14:23 UTC, merged

2022-02-07 06:20 UTC, YeonghyeonKO commented on lib/screens/profiles/other_profiles_body.dart
> +          if (!isMe) MessageSendButton(profile),
@gajagajago 
ProfileNickname 및 ProfileWebButtons 위젯 내부에서 `context.read<Authenticate>().isMe(profile.id)`을 통해 boolean을 호출할 수 있습니다. 하지만 해당 방식은 provider를 두 번 호출해야 한다는 점, 그리고 MessageSendButton의 노출 여부를 이미 parent에서 사용하고 있으므로 child 위젯인 ProfileNickname 및 ProfileWebButtons에 내려보내 줬습니다.
나머지 불필요한 호출은 준열님 의견 반영하여 Authenticate에 넣어 적재적소에서 호출하는 식으로 수정했습니다.
참고 바랍니다!