Feature/api post
wafflestudio/guam-community-client pull request #48
Opened 2022-02-13 16:13 UTC by YeonghyeonKO

> resolves #44 

- [ ] 게시글 미리보기

- [ ] 게시글 세부 페이지
 
- [ ] 댓글

### ToDo 
- Server API 수정 완료 시 각종 변경할 것들이 있음. ///주석 참고

2022-02-14 01:42 UTC, gajagajago requested changes
Left few comments.

2022-02-14 01:42 UTC, gajagajago commented on lib/models/boards/post.dart
> +  final Category.Category category; // ex) 데이터분석, 개발, 디자인
Category.Category 로 해야하는 이유가 있나요?

2022-02-14 01:42 UTC, gajagajago commented on lib/providers/posts/posts.dart
> +    fetchPosts(boardId);
여기선 boardId로 fetch하는데 boardType으로 response를 받는다는 게 조금 맞지 않는 것 같습니다.

2022-02-14 01:42 UTC, gajagajago commented on lib/providers/posts/posts.dart
> +        queryParams: {"boardId": boardId.toString()},
toString 꼭 해야하나요?

2022-02-14 01:42 UTC, gajagajago commented on lib/screens/boards/boards_app.dart
> +            BoardsFeed(boardId: 5),
boardId hard coding 은 지양해야 합니다.

2022-02-14 01:42 UTC, gajagajago commented on lib/screens/boards/comments/comment_banner.dart
> +                isMe: widget.comment.profile.id == myProfile.id,
굳이 isMe를 여기서 넘겨줄 필요 없을 것 같습니다. 같은 context 공유하니 CommentMore에서 처리하는 게 나을듯

2022-02-14 01:42 UTC, gajagajago commented on lib/screens/boards/comments/comment_banner.dart
> +                isMe: widget.comment.profile.id == myProfile.id,
+ 레거시이긴 하지만, Profile myProfile을 이 파일에서 state로 initState에서 init하는데, 변하지 않는 부분이니 state로 관리하기 보단 그냥 read해서 쓰는 게 어떨까요.

2022-02-14 01:42 UTC, gajagajago commented on lib/screens/boards/comments/comment_more.dart
> +  final bool isMe;
ditto

2022-02-14 01:42 UTC, gajagajago commented on lib/screens/boards/posts/detail/post_detail.dart
> +  Future<Post> post;
Please add TODO: script here, just to be sure this gets changed.

2022-02-14 01:42 UTC, gajagajago commented on lib/screens/boards/posts/detail/post_detail_more.dart
> +  final bool isMe;
ditto. Delete isMe parameter, check it inside here.

2022-02-14 02:00 UTC, YeonghyeonKO commented on lib/models/boards/post.dart
> +  final Category.Category category; // ex) 데이터분석, 개발, 디자인
@ Category라는 내부 라이브러리가 따로있더라구요 ㅋㅋㅋㅋ 하필..

2022-02-14 02:01 UTC, YeonghyeonKO commented
@gajagajago 리뷰 확인했습니다. 오늘 중으로 반영해서 RE-REVIEW REQUEST하겠습니다!

2022-02-15 00:32 UTC, gajagajago commented on lib/screens/boards/boards_type.dart
> +];
@YeonghyeonKO todo comment 하나 남겨주세요. 현재 일반 comment와 todo comment가 분리되지 않아 나중에 잘 안 찾아질 수 있습니다. 
ex) // TODO: ~~

2022-02-15 00:33 UTC, gajagajago approved these changes

2022-02-15 00:33 UTC, gajagajago commented
LGTM. // TODO comment 남기는 건 policy로 하시죠

2022-02-15 02:10 UTC, merged