Feature/profiles
wafflestudio/guam-community-client pull request #7
Opened 2021-11-27 09:07 UTC by gajagajago

- [ ] 프로필 페이지
- [ ] 프로필 수정 페이지
- [ ] Skillset 수정페이지
- [ ] 이미지 변경 모달

2021-12-04 04:05 UTC, gajagajago commented
common text field conflict는 이 브랜치를 따라가면 됩니다.

2021-12-04 05:19 UTC, YeonghyeonKO requested changes
간단히 확인했습니다!
금방 해결할 수 있는 issue는 comment로 적어두었고, 약간 살펴봐야할 것은
iOS simulator에서 profile image가 렌더링되지 않는 문제가 있군요(기본 프로필 사진으로만 표출됨)

+ 제가 해결하려고 하는 문제인데, 사진(프사, 업로드사진 등)을 클릭하여 확대할 때 bottomNavigationBar가 항상 위에 덮여진다는 이슈가 있습니다. (그 예로, 프로필 수정 페이지에서 아이유 클릭해보시면 아실 듯!)

 머릿속에 떠오르는 해결방안으로는, provider에 boolean 변수 하나 설정해두고 전체 화면을 덮어야하는 곳에서만 toggle 하는 방식인데 워낙 bottomNavigationBar가 상단에 있어 좋은 방식인지는 잘 모르겠습니다!

2021-12-05 02:44 UTC, YeonghyeonKO commented
> 간단히 확인했습니다! 금방 해결할 수 있는 issue는 comment로 적어두었습니다.
> 
> * 약간 살펴봐야할 것은 iOS simulator에서 profile image가 렌더링되지 않는 문제가 있군요(기본 프로필 사진으로만 표출됨)
> 
> * 제가 해결하려고 하는 문제인데, 사진(프사, 업로드사진 등)을 클릭하여 확대할 때 bottomNavigationBar가 항상 위에 덮여진다는 이슈가 있습니다. (그 예로, 프로필 수정 페이지에서 아이유 클릭해보시면 아실 듯!)
> 
> > 머릿속에 떠오르는 해결방안으로는, provider에 boolean 변수 하나 설정해두고 전체 화면을 덮어야하는 곳에서만 toggle 하는 방식인데 워낙 bottomNavigationBar가 상단에 있어 좋은 방식인지는 잘 모르겠습니다!

간단하게 해결했습니다! Navigator 설정 값 중에 rootNavigator라는 boolean 값을 true로 설정해주면 항상 최상단(root) Navigator로 만들어주는군요 ㅎㅎ

참고 : https://stackoverflow.com/questions/60349741/what-is-the-use-of-rootnavigator-in-navigator-ofcontext-rootnavigator-true

2021-12-29 07:17 UTC, gajagajago commented on lib/screens/profiles/buttons/profile_skill_button.dart
> +      side: BorderSide(color: GuamColorFamily.grayscaleGray6),
e1이라 6인듯합니다

2021-12-29 07:24 UTC, gajagajago commented
사진 업로드는 서버 달고 하겠습니다. 사진 올리거나 내리면 바로 post할까 하는 문제 한번 얘기해보고 하려고요

2021-12-30 13:50 UTC, YeonghyeonKO approved these changes
develop 브랜치에서는 profile img를 id마다 다르게 두었는데 하나로 통일하신 이유가 있을까요?

2021-12-30 13:50 UTC, YeonghyeonKO commented on lib/screens/profiles/profile/profile_img.dart
> +                    imagePath: profileImg.urlPath),
프로필 사진 확대 시 BottomNavigationBar 잠시 숨기기 위해 `rootNavigator: true` 로 변경해두었습니다

2021-12-30 13:50 UTC, YeonghyeonKO commented on lib/commons/image/closable_image_expanded.dart
> -      ),
이전에 작업할 때 넣어두었던 불필요한 부분이라 삭제했습니다!

2021-12-30 15:08 UTC, merged